name: Nuget Publish to github
on:
  [workflow_dispatch]
jobs:
  publish:
    name: nuget publish to github packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Pack
      run: dotnet pack src/RulesEngine/RulesEngine.csproj --configuration Release
    - name: Publish
      run: find ./src/RulesEngine/bin/Release -iname "*.nupkg" | xargs dotnet nuget push -s https://nuget.pkg.github.com/microsoft/index.json -k ${{secrets.GITHUB_TOKEN}}
