name: Nuget Publish
on:
  [workflow_dispatch]
jobs:
  publish:
    name: nuget publish package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting the workflow"
      - name: Materialize Signing Key
        id: write_sign_key_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'key.snk'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack src/RulesEngine/RulesEngine.csproj --configuration Release -p:ContinuousIntegrationBuild=true -p:DelaySign=false -p:AssemblyOriginatorKeyFile=${{ steps.write_sign_key_file.outputs.filePath }}
      - name: Cleanup Key
        run: rm ${{ steps.write_sign_key_file.outputs.filePath }}
      - name: Publish to GitHub Packages
        run: find ./src/RulesEngine/bin/Release -iname "*.nupkg" | xargs dotnet nuget push --skip-duplicate -s https://nuget.pkg.github.com/timophe-91/index.json -k ${{secrets.GITHUB_TOKEN}}
      - name: Publish to Nuget.org
        run: find ./src/RulesEngine/bin/Release -iname "*.nupkg" | xargs dotnet nuget push --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
